// GENERATED by scripts/build-mimi-walk-atlas.mjs — do not edit by hand.
// Rebuild with: node scripts/build-mimi-walk-atlas.mjs

/** Atlas row per authored direction. Frame index = row * COLUMNS + poseIndex. */
export const ATLAS_ROW = {
  s: 0,
  se: 1,
  e: 2,
  n: 3,
  nw: 4,
} as const;

export type AtlasDirection = keyof typeof ATLAS_ROW;

export const MIMI_WALK_ATLAS = {
  key: "mimi-walk",
  path: "/assets/game/character/mimi-walk.png",
  frameWidth: 124,
  frameHeight: 231,
  columns: 3,
  /**
   * Height in atlas px of the neutral standing pose, averaged over the
   * directions. Player pins its sprite scale to this so Mimi's on-screen size
   * is a property of the art, not of whichever frame happens to be showing.
   */
  referenceStandingHeight: 222.55,
  /**
   * Transparent gap left below the feet inside each cell. The ground anchor is
   * at (frameWidth / 2, frameHeight - padBottom), which is what the sprite's
   * origin must be set to.
   */
  padBottom: 6,
} as const;

/** Pose slot within a direction's row. */
export const POSE = { neutral: 0, contactA: 1, contactB: 2 } as const;
